# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_JOB_ENV: 'Job Env'
    steps:
    - uses: actions/checkout@v3
      env:
        MY_STEPS_ENV: 'Step ENV'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install feedparser
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest              
      env:
        EMAIL_SENDER_NAME: ${{ secrets.EMAIL_SENDER_NAME }}
        EMAIL_SENDER_PASSWORD: ${{secrets.EMAIL_SENDER_PASSWORD }}
      run: |
        pytest
        ls -l
        echo $MY_WF_ENV
        echo $MY_JOB_ENV
        echo ${{ secrets.EMAIL_SENDER_NAME }}
        pwd
        python okta_rss_feed.py
    
